version: "3.9"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./config/postgres.env

  app:
    build: ./src/
    env_file:
      - ./config/postgres.env
      - ./config/app.env
    ports:
      - 8000
    depends_on:
      - db
    volumes:
      - ./src/app:/src/app
      - static:/src/app/static
      - media:/src/media
    command: >
      bash -c "poetry run alembic upgrade head
      && poetry run uvicorn --reload --host=0.0.0.0 --port=8000 app.main:app"

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static
      - media:/media
    depends_on:
      - app

volumes:
  dbdata:
  static:
  media: